[package]
name = "zuti"
version = "0.1.0"
edition = "2024"
authors = ["Wenew Zhang<wenewboy@gmail.com>"]
description = "Zuti - Storage management web service"
license = "MIT"
repository = "https://github.com/yourusername/zuti"

[package.metadata.deb]
maintainer = "Wenew Zhang<wenewboy@gmail.com>"
copyright = "2026 Your Name"
extended-description = "A web service for disk and storage pool management"
section = "admin"
priority = "optional"
assets = [
    ["target/release/zuti", "usr/bin/zuti", "755"],
    ["migrations/", "usr/share/zuti/migrations/", "644"],
    [".env.example", "etc/zuti/.env.example", "644"],
    ["db.sqlite", "usr/share/zuti/db/db.sqlite", "644"],
]
depends = "libc6, libssl3 | libssl1.1, libpam0g, openssl"

[dependencies]
actix-web = { version = "4.13.0", features = ["openssl"] }
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
diesel = { version = "2.2.0", features = ["sqlite", "r2d2"] }
dotenvy = "0.15"
uuid = { version = "1", features = ["v4"] }
jsonwebtoken = { version = "10.3", features = ["rust_crypto"] }
chrono = "0.4"
pam = "0.8"
regex = "1"
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
tempfile = "3"
