#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        mkdir -p /etc/zuti/certs /var/lib/zuti /var/log/zuti /.data/zuti
        ;;
    abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
